#! /usr/bin/env python3

import rclpy
from rclpy.node import Node
from sensor_msgs.msg import Range


class UltrasonicSubscriber(Node):
    def __init__(self):
        super().__init__('ultrasonic_subscriber')
        self.subscription = self.create_subscription(
            Range,
            'ultrasonic_range',
            self.listener_callback,
            10
        )
        self.subscription  # Prevent unused variable warning

    def listener_callback(self, msg):
        distance = msg.range
        self.get_logger().info(f'Received distance: {distance:.2f} meters')

def main(args=None):
    rclpy.init(args=args)
    ultrasonic_subscriber = UltrasonicSubscriber()
    try:
        rclpy.spin(ultrasonic_subscriber)
    except KeyboardInterrupt:
        pass
    finally:
        ultrasonic_subscriber.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
